name: state-switching
channels:
- conda-forge
- bioconda
dependencies:
- conda-forge::python
- conda-forge::pandas=1.1.3
- conda-forge::numpy
- conda-forge::scikit-learn=0.23.2
- conda-forge::umap-learn=0.4.6
- conda-forge::joblib
- conda-forge::matplotlib
- conda-forge::seaborn
- conda-forge::plotnine
- conda-forge::jupyter
- conda-forge::ipykernel
- conda-forge::nb_conda_kernels
- conda-forge::widgetsnbextension
- conda-forge::jupyter_contrib_nbextensions
- bioconda::harmonypy=0.0.5
- pip:
  - git+https://github.com/cytomining/pycytominer@c1aa34b641b4e07eb5cbd424166f31355abdbd4d
